### 주소검색 해들목휴먼빌
GET http://localhost:8080/okcert
X-insr-servicekey: Q29weXJpZ2h0IOKTkiBpbnN1cm9iby5jby5rciBBbGwgcmlnaHRzIHJlc2VydmVkLg==

### 주소검색 해들목휴먼빌
GET http://localhost:8080/okcert/hello2
X-insr-servicekey: Q29weXJpZ2h0IOKTkiBpbnN1cm9iby5jby5rciBBbGwgcmlnaHRzIHJlc2VydmVkLg==


### KG 이니시스 가상계좌 결제 파라미터
GET http://localhost:8080/kginicis/vacct/param


### KG 이니시스 가상계좌 결제 리턴 테스트
GET http://localhost:8080/kginicis/noti/house
    ?P_STATUS=00
    &P_RMESG1=



### mybatis null test
GET http://localhost:8080/users/vingorius@gmail.com/test
X-insr-servicekey: Q29weXJpZ2h0IOKTkiBpbnN1cm9iby5jby5rciBBbGwgcmlnaHRzIHJlc2VydmVkLg==

### mybatis null test
GET http://210.179.175.145/users/vingorius@gmail.com/test
X-insr-servicekey: Q29weXJpZ2h0IOKTkiBpbnN1cm9iby5jby5rciBBbGwgcmlnaHRzIHJlc2VydmVkLg==

