### 주소검색 해들목휴먼빌
GET http://localhost:8080/ww/juso?search=해들목휴먼빌
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

# ### 표제부 해들목휴먼빌
# GET http://localhost:8080/house/cover?sigungucd=11410&bjdongcd=11900&bun=0001&ji=0028
# X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

# ### 전유부 해들목휴먼빌
# GET http://localhost:8080/house/detail?sigungucd=11410&bjdongcd=11900&bun=0001&ji=0028&dongnm=
# X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

# ### 견젹요청 다세대주택: 해들목휴먼빌
# POST http://localhost:8080/house/quotes/danche?sigungucd=11410&bjdongcd=11900&bun=0001&ji=0028
# X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
