
### 2 부산광역시 해운대구 달맞이길117번다길 130-1
### 주소검색 
GET http://localhost:8080/house/juso?search=부산광역시 해운대구 달맞이길117번다길 130-1
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 표제부 
GET http://localhost:8080/house/cover?sigungucd=26350&bjdongcd=10600&bun=1493&ji=0005
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 견젹요청
POST http://localhost:8080/house/quotes/danche?sigungucd=26350&bjdongcd=10600&bun=1493&ji=0005
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 3 부산광역시 해운대구 우동 1388-4 대우마리나1차아파트
### 주소검색 
GET http://localhost:8080/house/juso?search=부산광역시 해운대구 우동 1388-4 대우마리나1차아파트
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 표제부 
GET http://localhost:8080/house/cover?sigungucd=26350&bjdongcd=10500&bun=1388&ji=0004
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 견젹요청
POST http://localhost:8080/house/quotes/danche?sigungucd=26350&bjdongcd=10500&bun=1388&ji=0004
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==


### 4 부산광역시 해운대구 달맞이길117번가길 98 아남하이츠3차 
GET http://localhost:8080/house/juso?search=부산광역시 해운대구 달맞이길117번가길 98 아남하이츠3차
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 표제부 
GET http://localhost:8080/house/cover?sigungucd=26350&bjdongcd=10600&bun=1501&ji=0004
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 견젹요청
POST http://localhost:8080/house/quotes/danche?sigungucd=26350&bjdongcd=10600&bun=1501&ji=0004
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==


### 5 부산광역시 해운대구 재반로270번길 37-34 정우빌라. 공동주택과 단독주택이 같이 있음. 각각의 단가 구하는 방식으로 수정.
GET http://localhost:8080/house/juso?search=부산광역시 해운대구 재반로270번길 37-34
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 표제부 
GET http://localhost:8080/house/cover?sigungucd=26350&bjdongcd=10300&bun=1584&ji=0008
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 견젹요청
POST http://localhost:8080/house/quotes/danche?sigungucd=26350&bjdongcd=10300&bun=1584&ji=0008
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 9 서울특별시 동대문구 왕산로28길 3-1
GET http://localhost:8080/house/juso?search=서울특별시 동대문구 왕산로28길 3-1
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 표제부 
GET http://localhost:8080/house/cover?sigungucd=11230&bjdongcd=10200&bun=23&ji=24
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 견젹요청
POST http://localhost:8080/house/quotes/danche?sigungucd=11230&bjdongcd=10200&bun=23&ji=24
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==


### 17 경기도 성남시 수정구 성남대로1379번길 15-1
### 주소검색 
GET http://localhost:8080/house/juso?search=경기도 성남시 수정구 성남대로1379번길 15-1
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 표제부
GET http://localhost:8080/house/cover?sigungucd=41131&bjdongcd=10700&bun=0583&ji=0002
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 전유부
GET http://localhost:8080/house/detail?sigungucd=41131&bjdongcd=10700&bun=0583&ji=0002&dongnm=
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 견젹요청
POST http://localhost:8080/house/quotes/danche?sigungucd=41131&bjdongcd=10700&bun=0583&ji=0002
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==







### 표제부 다세대: 서울특별시 서대문구 증가로24가길 33
GET http://localhost:8080/house/cover?sigungucd=11410&bjdongcd=11900&bun=0002&ji=0007
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 견젹요청 다세대: 서울특별시 서대문구 증가로24가길 33 
POST http://localhost:8080/house/quotes/danche?sigungucd=11410&bjdongcd=11900&bun=0002&ji=0007
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 표제부 일반주택:  서울특별시 서대문구 증가로24다길 5 
GET http://localhost:8080/house/cover?sigungucd=11410&bjdongcd=11900&bun=0002&ji=0067
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 견젹요청 일반주택:  서울특별시 서대문구 증가로24다길 5 
POST http://localhost:8080/house/quotes/danche?sigungucd=11410&bjdongcd=11900&bun=0002&ji=0067
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==


###  주소검색
GET http://localhost:8080/house/juso?search=두산더랜드파크
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 표제부 두산더랜드파크
GET http://localhost:8080/house/cover?sigungucd=11500&bjdongcd=10500&bun=0757&ji=0000
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 견젹요청 단체 두산더랜드파크, 주택화재 대상 아님->406 error
POST http://localhost:8080/house/quotes/danche?sigungucd=11500&bjdongcd=10500&bun=0757&ji=0000
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==


### 표제부 해들목휴먼빌
GET http://localhost:8080/house/cover?sigungucd=11410&bjdongcd=11900&bun=0002&ji=0002
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
### 전유부 해들목휴먼빌
GET http://localhost:8080/house/detail?sigungucd=11410&bjdongcd=11900&bun=0002&ji=0002&dongnm=
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==


### 견젹요청 단체 해들목휴먼빌
POST http://localhost:8080/house/quotes/danche?sigungucd=11410&bjdongcd=11900&bun=0002&ji=0002
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 표제부 서울특별시 동작구 등용로 127(현대아파트)
GET http://localhost:8080/house/cover?sigungucd=11590&bjdongcd=10800&bun=0502&ji=0000
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

### 전유부 서울특별시 동작구 등용로 127(현대아파트) : Data가 너무 많다. -> 동요청
GET http://localhost:8080/house/detail?sigungucd=11590&bjdongcd=10800&bun=0502&ji=0000&dongnm=105동
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==


### 견젹요청 단체 서울특별시 동작구 등용로 127(현대아파트)
POST http://localhost:8080/house/quotes/danche?sigungucd=11590&bjdongcd=10800&bun=0502&ji=0000
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==

###
{
  "sigungucd":"11410",
  "bjdongcd":"11900",
  "bun":"0002",
  "ji":"0002"
}
### 견적요청 세대별 :해들목휴먼빌 501호 - 표제부 1, 전유부 1
POST http://localhost:8080/house/quotes/sedae
X-insr-servicekey: sdfsafsaf9osldfsafdosdfsfasf==
content-type: application/json

{
    "cover":{
    "naRoadCd": 114104136335,
    "oudrMechUtcnt": 0,
    "splotNm": "",
    "ugrndFlrCnt": 0,
    "pmsnoYear": 2016,
    "roofCd": 10,
    "hoCnt": 3,
    "naSubBun": 0.0,
    "mgmBldrgstPk": "11410-100223282",
    "oudrAutoUtcnt": 8,
    "crtnDay": 20200427,
    "totDongTotArea": 930.99,
    "atchBldCnt": 0,
    "dongNm": "해들목휴먼빌",
    "stcnsDay": 20161112,
    "block": "",
    "indrMechArea": 0,
    "archArea": 240.26,
    "pmsnoGbCd": 1101,
    "regstrGbCdNm": "집합",
    "gnBldCert": 0,
    "vlRatEstmTotArea": 930.99,
    "atchBldArea": 0,
    "platPlc": "서울특별시 서대문구 북가좌동 1-28번지",
    "etcPurps": "공동주택(다세대주택 및 근린생활시설)",
    "mainAtchGbCdNm": "주건축물",
    "bldNm": "해들목휴먼빌",
    "oudrMechArea": 0,
    "rideUseElvtCnt": 1,
    "strctCd": 21,
    "bjdongCd": 11900,
    "indrAutoArea": 0,
    "roofCdNm": "(철근)콘크리트",
    "naMainBun": 91.0,
    "bcRat": 51.56,
    "regstrKindCd": 3,
    "totArea": 930.99,
    "oudrAutoArea": 0,
    "sigunguCd": 11410,
    "strctCdNm": "철근콘크리트구조",
    "vlRat": 199.78,
    "ji": "0028",
    "engrEpi": 0,
    "gnBldGrade": "",
    "mainPurpsCd": "02000",
    "platGbCd": 0,
    "rserthqkDsgnApplyYn": 1,
    "naUgrndCd": 0,
    "bylotCnt": 1,
    "regstrGbCd": 2,
    "grndFlrCnt": 6,
    "etcStrct": "철근콘크리트구조",
    "indrAutoUtcnt": 5,
    "fmlyCnt": 0,
    "lot": "",
    "emgenUseElvtCnt": 0,
    "pmsnoKikCdNm": "건축과",
    "indrMechUtcnt": 0,
    "itgBldGrade": "",
    "heit": 17.2,
    "regstrKindCdNm": "표제부",
    "engrRat": 0,
    "rserthqkAblty": "G0.239 내진등급7",
    "itgBldCert": 0,
    "pmsnoGbCdNm": "신축허가",
    "rnum": 1,
    "pmsnoKikCd": 3120159,
    "etcRoof": "(철근)콘크리트(평스라브)",
    "engrGrade": "",
    "mainPurpsCdNm": "공동주택",
    "useAprDay": 20170601,
    "platArea": 466,
    "hhldCnt": 16,
    "mainAtchGbCd": 0,
    "pmsDay": 20160929,
    "naBjdongCd": 11901,
    "bun": "0001",
    "newPlatPlc": "서울특별시 서대문구 증가로20가길 91"
  },
    "detail":{
    "naRoadCd": 114104136335,
    "splotNm": "",
    "mainPurpsCd": "02003",
    "platGbCd": 0,
    "flrGbCd": 20,
    "naUgrndCd": 0,
    "regstrGbCd": 2,
    "etcStrct": "철근콘크리트구조",
    "lot": "",
    "naSubBun": 0.0,
    "mgmBldrgstPk": "11410-100223294",
    "crtnDay": 20181001,
    "hoNm": 501,
    "dongNm": "해들목휴먼빌",
    "regstrKindCdNm": "전유부",
    "block": "",
    "flrNo": 5.0,
    "flrNoNm": "5층",
    "area": 28.21,
    "rnum": 21,
    "regstrGbCdNm": "집합",
    "exposPubuseGbCdNm": "전유",
    "platPlc": "서울특별시 서대문구 북가좌동 1-28번지",
    "etcPurps": "공동주택(다세대주택)",
    "mainAtchGbCdNm": "주건축물",
    "mainPurpsCdNm": "다세대주택",
    "bldNm": "해들목휴먼빌",
    "strctCd": 21,
    "bjdongCd": 11900,
    "flrGbCdNm": "지상",
    "mainAtchGbCd": 0,
    "naBjdongCd": 11901,
    "naMainBun": 91.0,
    "exposPubuseGbCd": 1,
    "regstrKindCd": 4,
    "sigunguCd": 11410,
    "bun": "0001",
    "strctCdNm": "철근콘크리트구조",
    "newPlatPlc": "서울특별시 서대문구 증가로20가길 91",
    "ji": "0028"
  }
}

###서버
GET http://210.179.175.146:8080/webadmin
